### ISSUE TITLE
Что за Ethereum address?

### ISSUE THREAD

**Issue by yuriyseriy** [Margot07008/wallet#38]
Здравствуйте
Подскажите, увидел в файле src/components/AddressInput/AddressInput.tsx (Margot07008/wallet) адрес эфир кошелька "0xC88F7666330b4b511358b7742dC2a3234710e7B1", откуда вы его взяли, кому он принадлежит?

**Comment by Margot07008** [comment]
Здравствуйте. Это обычный адрес кошелька, кому принадлежит - неизвестно Сам адрес взяла случайным образом.
